### ISSUE TITLE
New dev bugs

### ISSUE THREAD

**Issue by jtoumey** [etoumey/bodyStats#43]
As I get up to speed, I am going to look into a few issues that come up repeatedly in my development environment.

* When supplying incorrect credentials, I sometimes get the message `Login Success` followed shortly by `Login Failure`.
* Timeout message with Selenium:
```
Error fetching RHR Data...
Traceback (most recent call last):
  File "/Users/jtoumey/CodeRepositories/active/bodyStats/reportFetch.py", line 261, in fetchReports
    dateRangeRHR = downloadReport(browser)
  File "/Users/jtoumey/CodeRepositories/active/bodyStats/reportFetch.py", line 41, in downloadReport
    EC.presence_of_element_located((By.XPATH, dateXpath)))
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
```
* Fix a warning concerning a deprecated function call
```
Login Success
reportFetch.py:204: DeprecationWarning: use driver.switch_to.default_content instead
  browser.switch_to_default_content()
reportFetch.py:39: DeprecationWarning: use driver.switch_to.default_content instead
  browser.switch_to_default_content()
RHR Download Success! RHR_20190919_20190925.csv
reportFetch.py:218: DeprecationWarning: use driver.switch_to.default_content instead
  browser.switch_to_default_content()
```

**Comment by etoumey** [comment]
Moved this bug to version 3.0. 

The user that reported the issue will need to retest with v2.0 build.
